{"name": "Получение заметки по некорректному ID", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('http_client', <FixtureRequest for <Function test_get_note_by_invalid_id[123abc]>>)", "trace": "file C:\\Users\\f.palekhov\\Downloads\\NodeApiTEST\\TEST\\tests\\test_api.py, line 183\n      @allure.title(\"Получение заметки по некорректному ID\")\n      @pytest.mark.parametrize(\"invalid_id\", [\"invalid_string\", \"123abc\", \"!@#$\"])\n      def test_get_note_by_invalid_id(self, http_client, base_url, invalid_id):\nE       fixture 'http_client' not found\n>       available fixtures: _attach_last_response, allure_env, base_url, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, capteesys, doctest_namespace, existing_note_id, http, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\f.palekhov\\Downloads\\NodeApiTEST\\TEST\\tests\\test_api.py:183"}, "parameters": [{"name": "invalid_id", "value": "'123abc'"}], "start": 1759764478705, "stop": 1759764478705, "uuid": "e163d0f2-d574-40ba-97e7-267da8cf6f22", "historyId": "944c487232783b87fa638e9774e2867b", "testCaseId": "efeb17e83461f5117735527552790e0e", "fullName": "tests.test_api.TestNoteRetrieval#test_get_note_by_invalid_id", "labels": [{"name": "feature", "value": "Управление заметками"}, {"name": "story", "value": "Получение заметок"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestNoteRetrieval"}, {"name": "host", "value": "E4435"}, {"name": "thread", "value": "12124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}], "titlePath": ["tests", "test_api.py", "TestNoteRetrieval"]}